# Generated by Django 4.1.4 on 2023-01-12 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="")),
                ("lat", models.FloatField(default=0)),
                ("lng", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Расположение",
                "verbose_name_plural": "Расположения",
            },
        ),
        migrations.AlterModelOptions(
            name="ad",
            options={"verbose_name": "Объявление", "verbose_name_plural": "Объявления"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.RemoveField(
            model_name="ad",
            name="author",
        ),
        migrations.AddField(
            model_name="ad",
            name="category_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=20)),
                ("last_name", models.CharField(default="", max_length=20)),
                ("username", models.CharField(default="", max_length=20)),
                ("password", models.CharField(default="123", max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Пользователь"),
                            ("moderator", "Администратор"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("age", models.SmallIntegerField(default=0)),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ads.location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="author_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="ads.user"
            ),
            preserve_default=False,
        ),
    ]
