# Generated by Django 4.1.4 on 2023-01-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_location_alter_ad_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="address",
        ),
    ]
